version: "3.7"
services:

  eureka-service:
    image: eureka-service
    container_name: eureka-service
    build: 
      context: ./EurekaService
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    ports:
      - "8761:8761"
  
  configuration-service:
    image: configuration-service
    container_name: configuration-service
    build: 
      context: ./ConfigurationService
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - static-network
    ports:
      - "8888:8888"
    depends_on: 
      - eureka-service

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16